version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fakhrimarzouki199@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data-volume:/opt/keycloak/data/import
    ports:
      - "9090:8080"
    command:
      - "start-dev"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
      image: docker.elastic.co/logstash/logstash:7.11.2
      container_name: logstash
      volumes:
        - ./logstash/config/logstash.conf:/usr/share/logstash/logstash.conf
      ports:
        - "5000:5000"
      networks:
        - elk
      depends_on:
        - elasticsearch

  kibana:
      image: docker.elastic.co/kibana/kibana:7.11.2
      container_name: kibana
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"
      networks:
        - elk
      depends_on:
        - elasticsearch

networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge
  elk:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  keycloak-data-volume:
