version: '3.8'
services:
  discovery-service:
    build: ./discovery
    container_name: discovery-service
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8888

  config-service:
    build: ./config-server
    container_name: config-service
    ports:
      - '8888:8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - '8223:8223'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8223/actuator/health" ]
    depends_on:
      keycloak:
        condition: service_started
      discovery-service:
        condition: service_started
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8888
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - KEYCLOAK_SERVER_REALM=http://keycloak:8080/realms/dive-into
      - KEYCLOAK_SERVER_PROTOCOL=http://keycloak:8080/realms/dive-into/protocol/openid-connect/certs
      - KEYCLOAK_SERVER_URL=http://keycloak:8080

  school-service:
      build: ./school
      container_name: school-service
      ports:
        - '8070:8070'
      depends_on:
        config-service:
          condition: service_healthy
        postgresql:
          condition: service_started
          #https://docs.docker.com/network/drivers/bridge/
      environment:
        - CONFIG_SERVICE_URL=http://config-service:8888
        - DATABASE_URL=jdbc:postgresql://postgresql:5432/schools
        - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
        - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
        - APPLICATION_CONFIG_STUDENTS_URL=http://student-service:8090/api/v1/students

  student-service:
    build: ./student
    container_name: student-service
    ports:
      - '8090:8090'
    depends_on:
      config-service:
        condition: service_healthy
      postgresql:
        condition: service_started
        #https://docs.docker.com/network/drivers/bridge/
      school-service:
        condition: service_started
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8888
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/students
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - APPLICATION_CONFIG_SCHOOLS_URL=http://school-service:8070/api/v1/schools
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data-volume:/opt/keycloak/data/import
    ports:
      - "9090:8080"
    command:
      - "start-dev"

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fakhrimarzouki199@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  front-end:
    build: ../front-keycloak/front-keycloak/
    container_name: front-keycloak
    ports:
      - "4200:80"
    depends_on:
      gateway-service:
          condition: service_started

volumes:
  postgres:
  pgadmin:
  keycloak-data-volume:
