server:
  port: 8223
spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: SCHOOLS
          uri: lb://SCHOOLS
          predicates:
            - Path=/api/v1/schools/**

        - id: STUDENTS
          uri: lb://STUDENTS
          predicates:
            - Path=/api/v1/students/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_REALM:http://localhost:9090/realms/dive-into}
          jwk-set-uri: ${KEYCLOAK_SERVER_PROTOCOL:http://localhost:9090/realms/dive-into/protocol/openid-connect/certs}

  main:
    allow-bean-definition-overriding: true

jwt:
  auth:
    converter:
      resource-id: dive-into
      principle-attribute: preferred_username
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

realm: dive-into
server-url: ${KEYCLOAK_SERVER_URL:http://localhost:9090}
client-id: dive-into
grant-type: password
name: admin
password: admin
client-secret: YZgjFZpuaqN89UoXwcxjrReoWjvGTJup
