server:
  port: 8223
spring:
  application:
    name: gateway-auth
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: SCHOOLS
          uri: lb://SCHOOLS
          predicates:
            - Path=/api/v1/schools/**
          filters:
            - AuthenticationFilter
        - id: STUDENTS
          uri: lb://STUDENTS
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
  main:
    allow-bean-definition-overriding: true



