server:
  port: 8222
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/auth-service
          jwk-set-uri: http://localhost:9090/realms/auth-service/protocol/openid-connect/certs
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: SCHOOLS
          uri: lb://SCHOOLS
          predicates:
            - Path=/api/v1/schools/**
        - id: STUDENTS
          uri: lb://STUDENTS
          predicates:
            - Path=/api/v1/students/**
management:
  tracing:
    sampling:
      probability: 1.0
